// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1O2IsumrfHl9toRxJwkPqj_m2gsbWmg',
    appId: '1:390933390835:web:2d7820668206fa51c2de86',
    messagingSenderId: '390933390835',
    projectId: 'tiktok-clone-94529',
    authDomain: 'tiktok-clone-94529.firebaseapp.com',
    storageBucket: 'tiktok-clone-94529.appspot.com',
    measurementId: 'G-CQE38M9VR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABp_brQO8lR6DXjhJP8p86tq04mbTOOH8',
    appId: '1:390933390835:android:3edd48d2743f566ac2de86',
    messagingSenderId: '390933390835',
    projectId: 'tiktok-clone-94529',
    storageBucket: 'tiktok-clone-94529.appspot.com',
  );
}
